{{- if .Values.knative.serving.enabled }}
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: {{ include "knative-deployment.fullname" . }}
spec:
  # ...
  high-availability:
    replicas: 3  
  deployments:
  - name: webhook
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: webhook    
  - name: activator
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: activator          
  ingress:
    istio:
      enabled: false  
    kourier:
      enabled: true  
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"     
    autoscaler:
      enable-scale-to-zero: "true"      
{{- end }}