{{- if .Values.knative.eventing.enabled }}
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: {{ include "humio-instance.fullname" . }}
spec:
  # ...
  source:
    kafka:
      enabled: {{ .Values.knative.eventing.source.kafka }}
{{- end }}