{{- if .Values.knative.serving.enabled }}
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: {{ include "knative-deployment.fullname" . }}
spec:
  # ...
  ingress:
    istio:
      enabled: false  
    kourier:
      enabled: true  
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"     
{{- end }}