{{- if .Values.knative.serving.enabled }}
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: {{ include "knative-deployment.fullname" . }}
spec:
  # ...
  high-availability:
    replicas: 3  
  deployments:
  - name: webhook
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          - app.kubernetes.io/name:knative-serving
          - app.kubernetes.io/component-webhook
  resources:
  - container: activator
    requests:
      cpu: 300m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 250Mi
      ephemeral-storage: 4Gi
  - container: autoscaler
    requests:
      cpu: 300m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 250Mi
      ephemeral-storage: 4Gi    
  ingress:
    istio:
      enabled: false  
    kourier:
      enabled: true  
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"     
    autoscaler:
      enable-scale-to-zero: "true"      
{{- end }}